setup.sh: install latexindent perl dependencies
xu-cheng/latex-docker pull request #2
Opened 2020-11-07 15:37 UTC by 2014CAIS01

May be fix #1 but now I run these command in https://github.com/xu-cheng/texlive-action manually, but I think the setup should add in `setup.sh`

Appendices: https://latexindentpl.readthedocs.io/en/latest/appendices.html#lst-alpine-install

2020-11-07 16:01 UTC, xu-cheng requested changes
Thanks for the PR. However, can you try to install Perl dependencies from apk to avoid unnecessary dependencies. We want to keep the image as small as possible.

2020-11-07 16:01 UTC, xu-cheng commented on setup.sh
> +    perl-unicode-linebreak
Please move these to the "install system package" in the above.

2020-11-08 02:06 UTC, 2014CAIS01 commented on setup.sh
> +cpanm -n Unicode::GCString
It seems some packages like `perl-file-homedir` are in `testing` repo, so I try to add `http://dl-cdn.alpinelinux.org/alpine/edge/testing` in `/etc/apk/repositories`

https://github.com/xu-cheng/latex-docker/blob/15aa124ec39ea43a626983786cc60912c6927a80/setup.sh#L26

2020-11-09 17:37 UTC, merged

2020-11-09 18:41 UTC, xu-cheng commented
Thanks @2014CAIS01.